# Generated by Django 5.1 on 2024-08-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='article',
            new_name='post',
        ),
    ]
